### ISSUE TITLE
Update repo homepage link to docs.rs?

### ISSUE THREAD

**Issue by tcr** [facebookincubator/rust-partial-io#11]
If you chose, you could change the link to https://docs.rs/partial-io instead of facebookincubator. If not, the rationale exists in this issue if the question comes up again!

**Comment by sid0** [comment]
Yeah, good question! We didn't do that because docs.rs doesn't support optional features currently, and I thought documenting the `quickcheck` and `tokio` features would be useful.

**Comment by sid0** [comment]
docs.rs gained support for non-optional features, so I've switched the documentation on crates.io to it. I've also added it to the README.
