### ISSUE TITLE
Testing Duplex Streams

### ISSUE THREAD

**Issue by AljoschaMeyer** [facebookincubator/rust-partial-io#15]
Is there a good way to test duplex streams (`S: Read + Write`) with this library? I could not really find a good way to do this, although that might be because of my unfamiliarity with rust.

A simple solution would be to provide an `impl<R: Read> Read for PartialWrite<R> {...}` which simply delegates to the inner reader. That way, you could simply wrap a stream in both a PartialRead and a PartialWrite. Analogously, there would be an `impl<W: Write> Write for PartialRead<W> {...}`.

Or there could be new wrapper structs `PartialDuplex` and `PartialAsyncDuplex` which would each maintain two separate lists of `PartialOp`s, one for reads and one for writes.

**Comment by sid0** [comment]
I really like the first idea because it makes it clear what the operations list applies to. I'll see if I can put up a fix shortly. Thanks for reporting this!

**Comment by sid0** [comment]
Hey -- I've landed support for these and published version 0.2.3 -- could you give it a shot? Thanks!

**Comment by AljoschaMeyer** [comment]
Thanks for the fast update. It works (also with quickcheck) and suffices to express my use case.

**Comment by sid0** [comment]
Awesome, glad to hear that! :)
