### ISSUE TITLE
AsyncWrite does not notify task on WouldBlock during flush

### ISSUE THREAD

**Issue by AljoschaMeyer** [facebookincubator/rust-partial-io#17]
The PartialAsyncWrite does not notify the current task on WouldBlock errors [during flushing](https://github.com/facebookincubator/rust-partial-io/blob/master/src/async_write.rs#L130) (compare [`write` which does](https://github.com/facebookincubator/rust-partial-io/blob/master/src/async_write.rs#L115)), even though the doc comment [says it should](https://github.com/facebookincubator/rust-partial-io/blob/master/src/async_write.rs#L14).

**Comment by sid0** [comment]
Thank you so much for the report! You're absolutely right -- this is an oversight.

I'll try and get a fix + new release out by tomorrow. Thanks again.

**Comment by sid0** [comment]
Version 0.2.5 is out with the fix. Thanks.

**Comment by AljoschaMeyer** [comment]
Suddenly the tests pass instead of hanging forever =) Thanks a lot!
