### ISSUE TITLE
Quickcheck: Specify maximum for PartialOp::Limited(n)

### ISSUE THREAD

**Issue by AljoschaMeyer** [facebookincubator/rust-partial-io#19]
Maybe it's just because I'm unfamiliar with quickcheck, but how does one specify the maximum number that is generated for `PartialOp::Limited`? I could only find out how to control the errors.

I'm currently writing my tests like this:

```rust
quickcheck! {
      fn my_test(write_ops: PartialWithErrors<GenInterruptedWouldBlock>, read_ops: PartialWithErrors<GenInterruptedWouldBlock>) -> bool {
          let stream = TestDuplex::new();
          let stream = PartialAsyncWrite::new(stream, write_ops);
          let mut stream = PartialAsyncRead::new(stream, read_ops);

          // do stuff
          return false;
      }
  }
```
And I'd like to specify the maximum value put into a `PartialOp::Limited`

**Comment by sid0** [comment]
Thanks for the question!

So the way QuickCheck for Rust works is that there's a `size` parameter associated with the RNG. This parameter is set to 100 by default but can be controlled by you, the test writer.

The number of bytes in `PartialOp::Limited` is a [random number uniformly distributed between 1 and `size`](https://github.com/facebookincubator/rust-partial-io/blob/master/src/quickcheck_types.rs#L162). So changing `size` will allow you to change what range the number gets chosen from.

For an example of how to control `size`, see [this test in Mononoke](https://github.com/facebookexperimental/mononoke/blob/7dfac826d365b356233244c798aa1b39e49732e7/mercurial-bundles/src/changegroup/mod.rs#L70). The second parameter (50) is the size.

If a uniform distribution is insufficient, you can also write your own generator following the examples in [`quickcheck_types.rs`](https://github.com/facebookincubator/rust-partial-io/blob/master/src/quickcheck_types.rs).

Let me know if you need anything else! Thanks.

**Comment by sid0** [comment]
(You won't be able to use the `quickcheck!` macro in that case -- you'll have to create a new `QuickCheck` as shown in the Mononoke test)

**Comment by AljoschaMeyer** [comment]
Great, thanks for your help :)

**Comment by sid0** [comment]
It seems like this is resolved, so closing this. Please reopen if this is still unresolved.
