### ISSUE TITLE
Update quickcheck to 0.8

### ISSUE THREAD

**Issue by gyscos** [facebookincubator/rust-partial-io#23]
`partial-io:0.3` currently depends on `quickcheck:0.6`, while version 0.8 has been available for a few months now.

https://github.com/BurntSushi/quickcheck/releases

**Comment by sunshowers** [comment]
Thanks for letting me know!

This would be a semver breakage (i.e. would have to be 0.4), right?

**Comment by gyscos** [comment]
Yes, as it would break code currently depending on `quickcheck:0.6`.

**Comment by sunshowers** [comment]
Thanks! I'll try getting an update out in a day or so.

**Comment by sunshowers** [comment]
Turns out this is much more complicated than I expected, unfortunately. For FB-internal reasons I'm blocked on at least https://github.com/tomprogrammer/rust-ascii/issues/61, possibly some other crates.

**Comment by gyscos** [comment]
Now targetting quickcheck 0.9.0.
Is it still planned?

**Comment by sunshowers** [comment]
Going to try getting quickcheck 0.9 support out in the next couple of days (see #26). Really sorry about the delay!

**Comment by sunshowers** [comment]
I've released version 0.4.0 with an update to both quickcheck 0.9 and to futures 0.3/tokio 0.2. Thank you so much for waiting for so long, it took me a long time to finally get around to this.
